<?php
$db_name = "college_1";
function createDatabase()
{
    global $db_name;
    $createDbQuery = "CREATE DATABASE " . $db_name;
    #creating database
    pg_query($createDbQuery);
}
function dumpData()
{
    $data = array(array('alice', 'c', 'pp', 'des'), array('bob', 'c', 'pp', 'de1s'));
    $createTableQuery = "CREATE TABLE students (
        id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        firstName varchar(255),
        lastName varchar(255),
        address varchar(255),
        city varchar(255)
    );";
    pg_query($createTableQuery);

    $insertQuery = "insert into students (firstName, lastName, address, city) ";
    foreach ($data as $value) {
        $insertQueryWithValues = $insertQuery . "values('" . implode("','", $value) . "')";
        pg_query($insertQueryWithValues);
    }
}
